# This is a basic workflow to help you get started with Actions

name: Continuous Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Docker-Push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: varma1909/ticketing-ticket-service:latest
          build-args: |
            DB=${{ secrets.DB_CONNECT }}
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
        
  Azure-Kubernetes-Cluster:
    runs-on: ubuntu-latest

    needs: Docker-Push

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          az aks get-credentials --resource-group Ticketing_Software --name kubernetes-cluster
      - name: Restarting the Cluster
        run: kubectl rollout restart deployment ticketing-service-deployment
        
        
        
        
        
        
          
          
          
          
